function varargout = boxplotGrowthParameters(datafile,statistic,varargin)
% boxplotGrowthParameters - Generates a box plots of the average growth 
% parameters in each concentration/level of a specific condition 
%
% boxplotGrowthParameters(input,statistic)
% boxplotGrowthParameters(input,statistic,levels,strains,parameters)
% excelOutput = boxplotGrowthParameters(input,statistic,levels,strains,parameters)
%
% Required input
% datafile          There are three possible inputs:
%                   1) Empty vector will open a dialog window to choose an
%                      Excel-file generated by GrowthProfilerKinetics8
%                   2) String with full path and file name of an Excel-file
%                      generated by GrowthProfilerKinetics8
%                   3) Cell matrix generated by extractGrowthParameters
%                      or tuneGrowthKinetics
% statistic         String indicating which statistic to return: 'mean', 'SD'
%                   or 'relSD'.
% 
% Optional input
% levels            Numeric vector with concentrations/levels, e.g. [1,1.5,3,6]. 
%                   Give an empty vector to plot all concentrations/levels
% strains           Cell array of strings with names of strains to include. Give an empty vector to include all strains.
% parameters        Cell array of strings specifying one or more of the
%                   following parameters (leave empty to include all parameters):
%                   1) Lag phase (h)
%                   2) Growth duration (h)
%                   3) Average growth rate (1/h)
%                   4) Number of generations	
%                   5) Maximum specific growth rate (1/h)
%
%
% Optional output
% excelOutput       Structure with the following fields:
%                   means - cell with statistics of the mean values
%                    formatted for creating box plots in Excel
%                   errors - cell with statistics of the errors of the
%                    mean values formatted for creating box plots in Excel
%                   relativeErrors - cell with statistics of the relative errors of the
%                    mean values formatted for creating box plots in Excel

%% HANLDE INPUT
readExcelFlag = true;

if isempty(datafile)
    [filename, pathname] = uigetfile( {'*.xls;*.xlsx', 'EXCEL Files (*.xls, *.xlsx)';'*.*','All Files (*.*)'},'Open Excel data file');
    datafile = fullfile(pathname, filename);
    
    if isequal(filename,0) || isequal(pathname,0)
        disp('No valid file selected. Program ended.')
        return
    end
elseif iscell(datafile)
    readExcelFlag = false;    
end

levelList = [];
strainList = {};
parList = {};

if nargin > 2 && ~isempty(varargin{1})
    levelList = unique(varargin{1}); 
    if size(levelList,2) == 1, levelList = reshape(levelList,1,length(levelList)); end
end

if nargin > 3 && ~isempty(varargin{2})
    strainList = unique(varargin{2}); 
    if size(strainList,1) == 1, strainList = reshape(strainList,length(strainList),1); end
end

if nargin > 4 && ~isempty(varargin{3})
    parList = unique(varargin{3},'stable'); 
    if size(parList,2) == 1, parList = reshape(parList,1,length(parList)); end
end

%% IMPORT DATA
if readExcelFlag
    [~,~,datafile] = xlsread(datafile,1);    
end

strains = datafile(2:end,1);
condition = datafile{2,2};
levels = datafile(2:end,3); levels = reshape([levels{:}],size(levels));
unit = datafile{2,4};

allParameters = {'Lag phase (h)' 'Growth duration (h)'	'Average growth rate (1/h)'	'Number of generations'	'Maximum OD' 'Maximum specific growth rate (1/h)'};
isPars = ismember(datafile(1,:),allParameters);
availablePars = datafile(1,isPars);
allParameterData = cell2mat(datafile(2:end,isPars));

%% DEFINE LISTS
if isempty(levelList)    
    levelList = unique(levels)';
end
numLevels = length(levelList);
isLevels = ismember(levels,levelList);

if isempty(strainList)
    strainList = unique(strains);
end
numStrains = length(strainList)
isStrains = ismember(strains,strainList);

if isempty(parList)
    parList = availablePars;
end
numPars = length(parList);
isPars = ismember(availablePars,parList);

% Define new lists and data matrix
levels = levels(isLevels & isStrains);
strains = strains(isLevels & isStrains);
%parameters = parameters(isPars);
dataMatrix = allParameterData(isLevels & isStrains, isPars);

%% CALCULATE GROUP STATISTICS
% Calculate statistics for each strain and condition
[means,sds,gnames,numElements] = grpstats(dataMatrix,{strains,levels},{'mean','std','gname','numel'});
levelsStats = str2double(gnames(:,2));

% Remove statistics based on less than 2 elements
isLow = numElements < 2;
means(isLow) = NaN;
sds(isLow) = NaN;
relSDs = sds./means*100;

% Select statistic based on user input
switch statistic
    case 'mean'
        stat.values = means;        
    case 'SD'
        stat.values = sds;        
    case 'relSD'
        stat.values = relSDs;        
end

% Calculate number of strains in each condition
strainCounts = grpstats(stat.values(:,1),levelsStats,{'numel'}) %The values should be the same for all parameters, hence only the first column is needed

% Calculate statistics for each condition
[stat.medians,stat.P25s,stat.P75s,stat.TopExtremes,stat.LowExtremes] = grpstats(stat.values,levelsStats,{@median, @prctile25, @prctile75, @TopExtreme, @LowExtreme});

%% GENERATE OUTPUT
if nargout < 1 %Create boxplots of the data
    figure
    bar(strainCounts./numStrains*100)
    ylabel('Strains with data (%)')
    if ~isnan(unit)
        xlabel([condition ' (' unit ')']);
    else
        xlabel(condition);
    end
    set(gca,'Xticklabel',unique(levelsStats))
    
    for i = 1:numPars
        id = strfind(parList{i},'(');
        if isempty(id)
            par = parList{i};
            punit = '';
        else
            par = parList{i}(1:id-1);
            punit = parList{i}(id:end);
        end
        
        
        switch statistic
            case 'mean'                
                sYlabel = parList{i};
            case 'SD'                          
                sYlabel = [par ' SD ' punit]; 
            case 'relSD'                                 
                sYlabel = [par ' relative error (%)']; 
        end
        
        figure
        boxplot(stat.values(:,i),levelsStats)
        ylabel(sYlabel)
        if ~isnan(unit)
            xlabel([condition ' (' unit ')']);
        else
            xlabel(condition);
        end        
        set(gca,'Xticklabel',unique(levelsStats));        
    end    
    
else %Put the statistics in a cell matrix
    if numLevels < 3, cols = 3; else cols = 1+numLevels; end
    
    M = cell(numLevels+4,cols);
    if ~isnan(unit)
        M(1,1:3) = {['Level (' unit ')'], 'Strains', 'Relative number (%)'};
    else
        M(1,1:3) = {'Level', 'Strains', 'Relative number (%)'};
    end
    
    M(2:1+numLevels,1) = num2cell(levelList(:));
    M(2:1+numLevels,2) = num2cell(strainCounts(:));
    M(2:1+numLevels,3) = num2cell(strainCounts(:)./numStrains*100);
    
    for i = 1:numPars
        outliers = cell(1,numLevels);
        maxNumOutliers = 0;
        
        M1 = cell(15,cols);
        if ~isnan(unit)
            M1(:,1) = {'Parameter';['Level (' unit ')'];'Low extreme';'25th percentile';'Median';'75th percentile';'Top extreme';'';'Box 1 (hidden)';'Box 2 (lower)';'Box 3 (upper)';'';'Whisker top';'Whisker bottom';''};
        else
            M1(:,1) = {'Parameter';'Level';'Low extreme';'25th percentile';'Median';'75th percentile';'Top extreme';'';'Box 1 (hidden)';'Box 2 (lower)';'Box 3 (upper)';'';'Whisker top';'Whisker bottom';''};
        end
        
        M1{1,2} = parList{i};
        M1(2,2:1+numLevels) = num2cell(levelList);
        
        for j = 1:numLevels
            M1{3,1+j} = stat.LowExtremes(j,i);
            M1{4,1+j} = stat.P25s(j,i);
            M1{5,1+j} = stat.medians(j,i);
            M1{6,1+j} = stat.P75s(j,i);
            M1{7,1+j} = stat.TopExtremes(j,i);
            
            M1{9,1+j} = stat.P25s(j,i); %stat.medians(j,i);
            M1{10,1+j} = stat.medians(j,i) - stat.P25s(j,i);
            M1{11,1+j} = stat.P75s(j,i) - stat.medians(j,i);
            
            M1{13,1+j} = stat.TopExtremes(j,i) - stat.P75s(j,i);
            M1{14,1+j} = stat.P25s(j,i) - stat.LowExtremes(j,i);
            
            isOutlier = stat.values(:,i) < stat.LowExtremes(j,i) | stat.values(:,i) > stat.TopExtremes(j,i);                
            ols = stat.values(isOutlier & (levelsStats == levelList(j)),i);
                        
            if numel(ols) > maxNumOutliers
                maxNumOutliers = numel(ols);
            end         
            outliers{j} = ols;
        end
        
%         M1(9,2:end) = M1(5,2:end);
%         M1(10,2:end) = num2cell( cell2num(M1(5,2:end)) - cell2num(M1(4,2:end)) );
%         M1(11,2:end) = num2cell( cell2num(M1(6,2:end)) - cell2num(M1(5,2:end)) );
        
        M2 = cell(maxNumOutliers+4,cols);
        M2(1,1:numLevels+1) = [{'Outliers'}, num2cell(1:numLevels)];
        for j = 1:numLevels
            ols = outliers{j};
            M2(2:1+length(ols),1+j) = num2cell(ols);
        end
        
        M = [M;M1;M2]; %#ok<AGROW>
    end
    
    varargout{1} = M;
end


%% AUXILIARY FUNCTIONS
% -------------------------------------------------------------------------
function p25 = prctile25(X)
p25 = prctile(X,25);

% -------------------------------------------------------------------------
function p75 = prctile75(X)
p75 = prctile(X,75);

% -------------------------------------------------------------------------
function Y = TopExtreme(X)
%Maximum whisker length w. The default is a w of 1.5. Points are drawn as outliers if they are larger than q3 + w(q3 – q1) or smaller than q1 – w(q3 – q1), where q1 and q3 are the 25th and 75th percentiles, respectively. The default of 1.5 corresponds to approximately +/–2.7? and 99.3 coverage if the data are normally distributed. The plotted whisker extends to the adjacent value, which is the most extreme data value that is not an outlier.
if isempty(X)
    Y = NaN;
else
    
    P = prctile(X,[25,75]);
    w = P(2) + 1.5*(P(2) - P(1));
    if w > max(X);
        Y = max(X);
    else
        Y = max(X(X <= w));
    end
end

% -------------------------------------------------------------------------
function Y = LowExtreme(X)
%Maximum whisker length w. The default is a w of 1.5. Points are drawn as outliers if they are larger than q3 + w(q3 – q1) or smaller than q1 – w(q3 – q1), where q1 and q3 are the 25th and 75th percentiles, respectively. The default of 1.5 corresponds to approximately +/–2.7? and 99.3 coverage if the data are normally distributed. The plotted whisker extends to the adjacent value, which is the most extreme data value that is not an outlier.
if isempty(X)
    Y = NaN;
else
    P = prctile(X,[25,75]);
    w =  P(1) - 1.5*(P(2) - P(1));
    if w < min(X)
        Y = min(X);
    else
        Y = min(X(X >= w));
    end
end
% -------------------------------------------------------------------------

