function results = calcRobustnessRanking(results,parWeights)
% calcRobustnessRanking - Calculates the performance and robustness scores
% and performs a variability analysis on the rankings.
%
% results = calcRobustnessRanking(input,parWeights)
%
% This file is used by calcStrainRanking.
%
% Required input
% input             Structure generated by calcStrainRanking
% 
% parWeights        Numeric vector with the weight for each parameter:%                   
%                   1) Lag phase (h)
%                   2) Growth duration (h)
%                   3) Average growth rate (1/h)
%                   4) Number of generations	
%                   5) Maximum specific growth rate (1/h)
%                   Leave empty to use equal weight for all paramteres, i.e. [1 1 1 1 1]
%                   Weights will automatically be adjusted to a sum of
%                   five.
%
% Output
% results          Structure with the following fields:
%                   


%% DEFINE LISTS
strainList = results.strainList;
levelList = results.levelList;
numLevels = length(levelList);
numStrains = length(strainList);
numPars = length(parWeights);


%% CACLULATE PERFORMACE AND ROBUSTNESS SCORES
parScores = results.parameters.scores;
parErrors = results.parameters.errors;

perfScores = zeros(numStrains,numLevels);
perfErrors = zeros(numStrains,numLevels);

for p = 1:numPars
    performance.scores{p} = zeros(numStrains,numLevels);
    performance.errors{p} = zeros(numStrains,numLevels);    
    
    perfScores = perfScores + parWeights(p).*parScores{p};
    perfErrors = perfErrors + (parWeights(p).*parErrors{p}).^2;
end
perfErrors = sqrt(perfErrors);

robustScore = sum(perfScores,2)./numLevels;
robustError = sqrt(sum(perfErrors.^2,2))./numLevels;

%% GATHER RESULTS
results.performance.scores = perfScores;
results.performance.errors = perfErrors;

results.robustness.scores = robustScore;
results.robustness.errors = robustError;

%% PERFORM THE RVA (RANK VARIABILITY ANALYSIS)
results.RVA = rva(robustScore,perfScores,perfErrors,strainList,numLevels);

